#%RAML 1.0
title: Resources simple

/:
 description: Root

/basicResource:
  displayName: basic resource
  description: Short description

/parentResource:
  /innerResource:
    displayName: inner resource
    description: Short description
