#%RAML 1.0
title: My API

/basic:
  get:
    responses:
      200:
        body:
          application/json:
            description: Object body
            properties:
              stringProperty: string
              integerProperty:
                type: integer
                # Example below is not imported as an example is already defined higher in the type hierarchy
                example: 123
            example:
              stringProperty: toto
              integerProperty: 1

      201:
        body:
          application/json:
            type: array
            items:
              properties:
                integerProperty: integer
                objectProperty:
                  properties:
                    stringSubProperty:
                      type: string
                      example: "inner property"